services:
  postgres-db:
    image: postgres:16.8
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leaderboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-standalone:
    image: redis:latest
    container_name: redis-standalone
    ports:
      - "6379:6379"
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.0-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  leaderboard-backend:
    image: leaderboard-backend:latest
    container_name: leaderboard-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-standalone:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=changeme
      - JWT_EXPIRES_IN=1d
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=leaderboard_db
      - DB_ROLE=postgres
      - REDIS_URL=redis://redis-standalone:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SOCKET_SERVER_URL=http://localhost:3000
      - CRON_DISTRIBUTION_TIME=0 23 * * 0
    networks:
      - leaderboard-network
    restart: on-failure

networks:
  leaderboard-network:
    driver: bridge

volumes:
  postgres_data:
