apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: your-registry/node-project:latest
          command: ["node", "dist/index.js"]
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-service:5672"
            - name: REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-service:6379,redis-cluster-1.redis-service:6379,redis-cluster-2.redis-service:6379"
          ports:
            - containerPort: 3000
