apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-worker
spec:
  replicas: 100
  selector:
    matchLabels:
      app: node-worker
  template:
    metadata:
      labels:
        app: node-worker
    spec:
      containers:
        - name: node-worker-container
          image: bfkbt14/leaderboard-backend:latest
          # Worker mod
          command: ["node", "dist/worker.js"]
          env:
            - name: RABBITMQ_URL
              value: "amqp://leaderboard-rabbitmq:5672"
            - name: REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-service:6379,redis-cluster-1.redis-service:6379,redis-cluster-2.redis-service:6379"
