apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-worker-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-worker
  minReplicas: 10
  maxReplicas: 100
  # v2 HPA metrics:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
